(function(){
  $(document).ready(function(){
    $(".year-2020").click(function(){
      $(".year-content-2020").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2019").click(function(){
      $(".year-content-2019").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2018").click(function(){
      $(".year-content-2018").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2017").click(function(){
      $(".year-content-2017").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2016").click(function(){
      $(".year-content-2016").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2015").click(function(){
      $(".year-content-2015").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2014").click(function(){
      $(".year-content-2014").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2013").click(function(){
      $(".year-content-2013").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2012").click(function(){
      $(".year-content-2012").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2011").click(function(){
      $(".year-content-2011").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2010").click(function(){
      $(".year-content-2010").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2009").click(function(){
      $(".year-content-2009").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2008").click(function(){
      $(".year-content-2008").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2007").click(function(){
      $(".year-content-2007").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2006").click(function(){
      $(".year-content-2006").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2005").click(function(){
      $(".year-content-2005").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2004").click(function(){
      $(".year-content-2004").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2003").click(function(){
      $(".year-content-2003").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2002").click(function(){
      $(".year-content-2002").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2001").click(function(){
      $(".year-content-2001").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-2000").click(function(){
      $(".year-content-2000").slideToggle("slow");
    });
  });
  $(document).ready(function(){
    $(".year-1999").click(function(){
      $(".year-content-1999").slideToggle("slow");
    });
  });

  })();
